# Generated by Django 4.2.7 on 2023-11-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(default='1.jpg', upload_to='newsphoto/'),
        ),
    ]
